(defvar mandelbrot-empty " ")
(defvar mandelbrot-quadrant-upper-left "▘")
(defvar mandelbrot-quadrant-upper-right "▝")
(defvar mandelbrot-upper-half-block "▀")
(defvar mandelbrot-quadrant-lower-left  "▖")
(defvar mandelbrot-left-half-block "▌")
(defvar mandelbrot-quadrant-upper-right-and-lower-left "▞")
(defvar mandelbrot-quadrant-upper-left-and-upper-right-and-lower-left "▛")
(defvar mandelbrot-quadrant-lower-right "▗")
(defvar mandelbrot-quadrant-upper-left-and-lower-right "▚")
(defvar mandelbrot-right-half-block "▐")
(defvar mandelbrot-quadrant-upper-left-and-upper-right-and-lower-right "▜")
(defvar mandelbrot-lower-half-block "▄")
(defvar mandelbrot-quadrant-upper-left-and-lower-left-and-lower-right "▙")
(defvar mandelbrot-quadrant-upper-right-and-lower-left-and-lower-right "▟")
(defvar mandelbrot-full-block "█")

(provide 'mandelbrot-utf-8)
